# Build target
FROM debian:13-slim AS lightrtos-qemu-build
ARG DEBIAN_FRONTEND=noninteractive
COPY qemu/ /qemu
RUN apt update && apt install -y build-essential git libglib2.0-dev meson ninja-build python3 python3-venv
RUN (cd /qemu && ./configure --target-list=avr-softmmu --prefix=/opt/qemu && make -j $(nproc) && make install)

# Runner target
FROM debian:13-slim as lightrtos-qemu-runner
ARG DEBIAN_FRONTEND=noninteractive
ENV PATH=${PATH}:/opt/qemu/bin
COPY --from=lightrtos-qemu-build /opt/qemu /opt/qemu
RUN apt update && apt install -y gdb-multiarch libglib2.0-dev lxterminal telnet
COPY qemu-container/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
