# Build target
FROM debian:13-slim AS lightrtos-qemu-build
ENV DEBIAN_FRONTEND=noninteractive

COPY qemu/ /qemu
COPY container/qemu-select-firmware.sh /qemu-select-firmware.sh

RUN apt update && apt install -y build-essential git libglib2.0-dev meson ninja-build python3 python3-venv
RUN (cd /qemu && ./configure --target-list=avr-softmmu && make -j $(nproc))
ENTRYPOINT ["/qemu-select-firmware.sh"]
